  # PyTorch Basics : Tensors & Gradients

In [5]:
!pip install torch numpy --quiet

In [6]:
import torch

# Tensors

PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a sinle number

In [7]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is a shorthand for `4.0`. It is used to indicate a python (and Pytorch) that you want to create a floating-point number. we can verify this by checking the `dtype` attribute of our tensor

In [8]:
t1.dtype

torch.float32

 ##### Note : If we wouldn't have written . after 4 then the datatype would have been `int64` 
 Always try to create float tensor so that all the operations are of floating type and there is no data loss. 

Let's try creating more complex tensors

In [9]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

Tensor makes all the `dtype` same, so `1.` was `float32`, so it made the whole vector as `float32`

In [10]:
# Matrix
t3 = torch.tensor([[5., 6],
                  [7 , 8],
                  [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [11]:
# 3D array
t4 = torch.tensor([
    [[11, 12, 13],
    [14, 15, 16]],
    [[17, 18, 19],
    [20, 21, 22.]]
])
t4

tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[17., 18., 19.],
         [20., 21., 22.]]])

Tensors can have any number of dimensions and different lengths along each dimensions. We can inspect the length along each dimension using the `.shape` property of tensor.

In [12]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

t1 is a single number, it doesn't have any shape. Its dimensionless. That's why an empty list occurs

In [13]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

t2 is a 1D vector. One number represent 1 dimension and 4 represent 4 elements that are present in that 1D array 

In [14]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

3 represent no.of rows and 2 represents no.of columns

## Tensor operation and gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [15]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created 3 tensors : x, w, b all numbers.

Let's create a new tensor `y` by combining these tensors

In [16]:
# Arithmetic Operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is tensor with the `3 * 4 + 5 = 17`. What makes PyTorch unique is that we can automatically compute the derivative of `y` w.r.t the tensors that have `required_grad` set to `True` i.e., w and b. This feature of PyTorch is called `autograd`(automatic gradients). 
To compute the derivative we can invoke the `.backward`method on our result `y`.

In [17]:
# Compute Derivatives
y.backward()

The derivates of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors.

In [18]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, `dy/dw` has the same value as `x` i.e., `3` and `dy/db` has the value '1'. 
#### Note : `x.grad` is `None` because `x` doesn't have `requires_grad` set to `True`.

The "grad" in `w.grad` stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular opeb-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing
* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

In [19]:
import numpy as np

In [20]:
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy to a PyTorch tensor using `torch.from_numpy`

In [21]:
# Convert the numpy array to a torch sensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types

In [22]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the `.numpy()` method of a tensor

In [25]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are 2 main reasons :
1. Autograd : The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. GPU Support : While working with massive dataset and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

With this, we complete our discussion of tensors and gradients in PyTorch, and we're ready to move on to the next topic: Linear regression.

In [26]:
!pip install jovian --upgrade

In [27]:
import jovian

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.com/ ):
API KEY: ········
[jovian] Committed successfully! https://jovian.com/roburishabh/1-pytorch-basics


'https://jovian.com/roburishabh/1-pytorch-basics'